name: Generate JSON sitemap

# Run every time you push to the main branch
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate JSON Sitemap
        run: |
          echo '{"urls": [' > sitemap.json
          first=true
          for file in $(find . -type f -name "*.html"); do
            if [ "$first" = true ]; then
              first=false
            else
              echo ',' >> sitemap.json
            fi
            echo "{\"url\": \"https://billvivino.github.io${file#.}\", \"lastmod\": \"$(date +%F)\"}" >> sitemap.json
          done
          echo ']}' >> sitemap.json

      - name: Commit JSON sitemap
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sitemap.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update JSON sitemap"
            git push
          fi
