name: Generate XML sitemap

# Run every time you push to the main branch
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate XML Sitemap
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          for file in $(find . -type f -name "*.html"); do
            if [[ "$file" == "./index.html" ]]; then
              loc="https://billvivinotechnology.com/"
            else
              loc="https://billvivinotechnology.com${file#.}"
            fi
            echo "  <url><loc>${loc}</loc><lastmod>$(date +%F)</lastmod></url>" >> sitemap.xml
          done
          echo '</urlset>' >> sitemap.xml

      - name: Commit XML sitemap
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sitemap.xml
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update XML sitemap"
            git push
          fi
